/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2
using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class GlobalPlannerActionResult : ActionResult<GlobalPlannerResult>
    {
        public const string RosMessageName = "moveit_msgs/GlobalPlannerActionResult";

        public GlobalPlannerActionResult() : base()
        {
            this.result = new GlobalPlannerResult();
        }

        public GlobalPlannerActionResult(Header header, GoalStatus status, GlobalPlannerResult result) : base(header, status)
        {
            this.result = result;
        }
    }
}
#endif
