/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Moveit;

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class GlobalPlannerResult : Message
    {
        public const string RosMessageName = "moveit_msgs/action/GlobalPlannerResult";

        //  Motion planning response from the global planner
        public MotionPlanResponse response { get; set; }

        public GlobalPlannerResult()
        {
            this.response = new MotionPlanResponse();
        }

        public GlobalPlannerResult(MotionPlanResponse response)
        {
            this.response = response;
        }
    }
}
#endif
