/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2


namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class HybridPlannerAction : Action<HybridPlannerActionGoal, HybridPlannerActionResult, HybridPlannerActionFeedback, HybridPlannerGoal, HybridPlannerResult, HybridPlannerFeedback>
    {
        public const string RosMessageName = "moveit_msgs/action/HybridPlannerAction";

        public HybridPlannerAction() : base()
        {
            this.action_goal = new HybridPlannerActionGoal();
            this.action_result = new HybridPlannerActionResult();
            this.action_feedback = new HybridPlannerActionFeedback();
        }

    }
}
#endif
