/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Moveit;

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class LocalPlannerResult : Message
    {
        public const string RosMessageName = "moveit_msgs/action/LocalPlannerResult";

        //  Result of the local planning operation
        public MoveItErrorCodes error_code { get; set; }
        //  Error message with more detailed information about the local planning result
        public string error_message { get; set; }

        public LocalPlannerResult()
        {
            this.error_code = new MoveItErrorCodes();
            this.error_message = "";
        }

        public LocalPlannerResult(MoveItErrorCodes error_code, string error_message)
        {
            this.error_code = error_code;
            this.error_message = error_message;
        }
    }
}
#endif
