/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2
using RosSharp.RosBridgeClient.MessageTypes.Std;
namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class PickupActionResult : ActionResult<PickupResult>
    {
        public const string RosMessageName = "moveit_msgs/action/PickupActionResult";

        public PickupActionResult() : base()
        {
            this.values = new PickupResult();
        }

        public PickupActionResult(Header header, string action, sbyte status, bool result, string id, PickupResult values) : base(header, action, status, result, id)
        {
            this.values = values;
        }
    }
}
#endif
