/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Geometry
{
    public class InertiaStamped : Message
    {
        public const string RosMessageName = "geometry_msgs/msg/InertiaStamped";

        //  An Inertia with a time stamp and reference frame.
        public Header header { get; set; }
        public Inertia inertia { get; set; }

        public InertiaStamped()
        {
            this.header = new Header();
            this.inertia = new Inertia();
        }

        public InertiaStamped(Header header, Inertia inertia)
        {
            this.header = header;
            this.inertia = inertia;
        }
    }
}
#endif
