/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Geometry
{
    public class Quaternion : Message
    {
        public const string RosMessageName = "geometry_msgs/msg/Quaternion";

        //  This represents an orientation in free space in quaternion form.
        public double x = 0;
        public double y = 0;
        public double z = 0;
        public double w = 1;

        public Quaternion()
        {
        }

        public Quaternion(double x, double y, double z, double w)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.w = w;
        }
    }
}
#endif
