/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Geometry
{
    public class TransformStamped : Message
    {
        public const string RosMessageName = "geometry_msgs/msg/TransformStamped";

        //  This expresses a transform from coordinate frame header.frame_id
        //  to the coordinate frame child_frame_id at the time of header.stamp
        // 
        //  This message is mostly used by the
        //  <a href="https://index.ros.org/p/tf2/">tf2</a> package.
        //  See its documentation for more information.
        // 
        //  The child_frame_id is necessary in addition to the frame_id
        //  in the Header to communicate the full reference for the transform
        //  in a self contained message.
        //  The frame id in the header is used as the reference frame of this transform.
        public Header header { get; set; }
        //  The frame id of the child frame to which this transform points.
        public string child_frame_id { get; set; }
        //  Translation and rotation in 3-dimensions of child_frame_id from header.frame_id.
        public Transform transform { get; set; }

        public TransformStamped()
        {
            this.header = new Header();
            this.child_frame_id = "";
            this.transform = new Transform();
        }

        public TransformStamped(Header header, string child_frame_id, Transform transform)
        {
            this.header = header;
            this.child_frame_id = child_frame_id;
            this.transform = transform;
        }
    }
}
#endif
