/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Geometry
{
    public class Vector3Stamped : Message
    {
        public const string RosMessageName = "geometry_msgs/msg/Vector3Stamped";

        //  This represents a Vector3 with reference coordinate frame and timestamp
        //  Note that this follows vector semantics with it always anchored at the origin,
        //  so the rotational elements of a transform are the only parts applied when transforming.
        public Header header { get; set; }
        public Vector3 vector { get; set; }

        public Vector3Stamped()
        {
            this.header = new Header();
            this.vector = new Vector3();
        }

        public Vector3Stamped(Header header, Vector3 vector)
        {
            this.header = header;
            this.vector = vector;
        }
    }
}
#endif
