/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if !ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Actionlib
{
    public class TestRequestAction : Message
    {
        public const string RosMessageName = "actionlib/TestRequestAction";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public TestRequestActionGoal action_goal { get; set; }
        public TestRequestActionResult action_result { get; set; }
        public TestRequestActionFeedback action_feedback { get; set; }

        public TestRequestAction()
        {
            this.action_goal = new TestRequestActionGoal();
            this.action_result = new TestRequestActionResult();
            this.action_feedback = new TestRequestActionFeedback();
        }

        public TestRequestAction(TestRequestActionGoal action_goal, TestRequestActionResult action_result, TestRequestActionFeedback action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }
    }
}
#endif
