/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if !ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Actionlib
{
    public class TestResult : Message
    {
        public const string RosMessageName = "actionlib/TestResult";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public int result { get; set; }

        public TestResult()
        {
            this.result = 0;
        }

        public TestResult(int result)
        {
            this.result = result;
        }
    }
}
#endif
