/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Std
{
    public class MultiArrayDimension : Message
    {
        public const string RosMessageName = "std_msgs/msg/MultiArrayDimension";

        //  This was originally provided as an example message.
        //  It is deprecated as of Foxy
        //  It is recommended to create your own semantically meaningful message.
        //  However if you would like to continue using this please use the equivalent in example_msgs.
        public string label { get; set; }
        // label of given dimension
        public uint size { get; set; }
        // size of given dimension (in type units)
        public uint stride { get; set; }
        // stride of given dimension

        public MultiArrayDimension()
        {
            this.label = "";
            this.size = 0;
            this.stride = 0;
        }

        public MultiArrayDimension(string label, uint size, uint stride)
        {
            this.label = label;
            this.size = size;
            this.stride = stride;
        }
    }
}
#endif
