/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using System.Runtime.Serialization;

namespace RosSharp.RosBridgeClient.MessageTypes.Sensor
{
    [DataContract]
    public class SetCameraInfoResponse : Message
    {
        [IgnoreDataMember]
        public const string RosMessageName = "sensor_msgs/SetCameraInfo";

        [DataMember]
        public bool success;
        //  True if the call succeeded
        [DataMember]
        public string status_message;
        //  Used to give details about success

        public SetCameraInfoResponse()
        {
            this.success = false;
            this.status_message = "";
        }

        public SetCameraInfoResponse(bool success, string status_message)
        {
            this.success = success;
            this.status_message = status_message;
        }
    }
}
