/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class ExecuteTrajectoryResult : Message
    {
        public const string RosMessageName = "moveit_msgs/ExecuteTrajectoryResult";

        //  Error code - encodes the overall reason for failure
        public MoveItErrorCodes error_code { get; set; }

        public ExecuteTrajectoryResult()
        {
            this.error_code = new MoveItErrorCodes();
        }

        public ExecuteTrajectoryResult(MoveItErrorCodes error_code)
        {
            this.error_code = error_code;
        }
    }
}
