/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class ExecuteTrajectoryActionResult : ActionResult<ExecuteTrajectoryResult>
    {
        public override string RosMessageName => "moveit_msgs/ExecuteTrajectoryActionResult";

        public ExecuteTrajectoryActionResult() : base()
        {
            this.result = new ExecuteTrajectoryResult();
        }

        public ExecuteTrajectoryActionResult(Header header, GoalStatus status, ExecuteTrajectoryResult result) : base(header, status)
        {
            this.result = result;
        }
    }
}
