/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Std
{
    public class TriggerResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "std_srvs/Trigger";

        public bool success;
        //  indicate successful run of triggered service
        public string message;
        //  informational, e.g. for error MessageTypes

        public TriggerResponse()
        {
            this.success = false;
            this.message = "";
        }

        public TriggerResponse(bool success, string message)
        {
            this.success = success;
            this.message = message;
        }
    }
}
