# Goal Def
uint8 type             # Type of file sending operation
uint8 SINGLE     = 0   # Send a single file
uint8 PACKAGE    = 1   # Send files of a package
uint8 RECURSIVE  = 2   # Send all files in a directory (recursively)
string identifier      # Either package_name/file_name for single file
                       #     or package_name for package
                       #     or path for directory
string[] types         # Extension of files to be transferred (e.g. .msg, .srv, .action)
---
# Result def
# Intentionally Left empty
---
# Feedback def
int16 number           # Totoal number of files to be transferred
int16 count            # Count of files transferred
string path            # Path of transferred file at origin
uint8[] content        # The content of the file in bytes
