/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using System.Runtime.Serialization;

namespace RosSharp.RosBridgeClient.MessageTypes.Geometry
{
    [DataContract]
    public class Accel : Message
    {
        [IgnoreDataMember]
        public const string RosMessageName = "geometry_msgs/Accel";

        //  This expresses acceleration in free space broken into its linear and angular parts.
        [DataMember]
        public Vector3 linear;
        [DataMember]
        public Vector3 angular;

        public Accel()
        {
            this.linear = new Vector3();
            this.angular = new Vector3();
        }

        public Accel(Vector3 linear, Vector3 angular)
        {
            this.linear = linear;
            this.angular = angular;
        }
    }
}
