/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using System.Runtime.Serialization;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Geometry
{
    [DataContract]
    public class PolygonStamped : Message
    {
        [IgnoreDataMember]
        public const string RosMessageName = "geometry_msgs/PolygonStamped";

        //  This represents a Polygon with reference coordinate frame and timestamp
        [DataMember]
        public Header header;
        [DataMember]
        public Polygon polygon;

        public PolygonStamped()
        {
            this.header = new Header();
            this.polygon = new Polygon();
        }

        public PolygonStamped(Header header, Polygon polygon)
        {
            this.header = header;
            this.polygon = polygon;
        }
    }
}
