/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Geometry
{
    public class PoseStamped : Message
    {
        public override string RosMessageName => "geometry_msgs/PoseStamped";

        //  A Pose with reference coordinate frame and timestamp
        public Header header { get; set; }
        public Pose pose { get; set; }

        public PoseStamped()
        {
            this.header = new Header();
            this.pose = new Pose();
        }

        public PoseStamped(Header header, Pose pose)
        {
            this.header = header;
            this.pose = pose;
        }
    }
}
