/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using System.Runtime.Serialization;

namespace RosSharp.RosBridgeClient.MessageTypes.Geometry
{
    [DataContract]
    public class Transform : Message
    {
        [IgnoreDataMember]
        public const string RosMessageName = "geometry_msgs/Transform";

        //  This represents the transform between two coordinate frames in free space.
        [DataMember]
        public Vector3 translation;
        [DataMember]
        public Quaternion rotation;

        public Transform()
        {
            this.translation = new Vector3();
            this.rotation = new Quaternion();
        }

        public Transform(Vector3 translation, Quaternion rotation)
        {
            this.translation = translation;
            this.rotation = rotation;
        }
    }
}
