/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

namespace RosSharp.RosBridgeClient.MessageTypes.Geometry
{
    public class Twist : Message
    {
        public const string RosMessageName = "geometry_msgs/Twist";

        //  This expresses velocity in free space broken into its linear and angular parts.
        public Vector3 linear { get; set; }
        public Vector3 angular { get; set; }

        public Twist()
        {
            this.linear = new Vector3();
            this.angular = new Vector3();
        }

        public Twist(Vector3 linear, Vector3 angular)
        {
            this.linear = linear;
            this.angular = angular;
        }
    }
}
