/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using System.Runtime.Serialization;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Geometry
{
    [DataContract]
    public class WrenchStamped : Message
    {
        [IgnoreDataMember]
        public const string RosMessageName = "geometry_msgs/WrenchStamped";

        //  A wrench with reference coordinate frame and timestamp
        [DataMember]
        public Header header;
        [DataMember]
        public Wrench wrench;

        public WrenchStamped()
        {
            this.header = new Header();
            this.wrench = new Wrench();
        }

        public WrenchStamped(Header header, Wrench wrench)
        {
            this.header = header;
            this.wrench = wrench;
        }
    }
}
