/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Tf2
{
    public class FrameGraphResponse : Message
    {
        public const string RosMessageName = "tf2_msgs/srv/FrameGraph";

        public string frame_yaml { get; set; }

        public FrameGraphResponse()
        {
            this.frame_yaml = "";
        }

        public FrameGraphResponse(string frame_yaml)
        {
            this.frame_yaml = frame_yaml;
        }
    }
}
#endif
