/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class MoveGroupSequenceFeedback : Message
    {
        public const string RosMessageName = "moveit_msgs/MoveGroupSequenceFeedback";

        //  The internal state that the move group action currently is in
        public string state { get; set; }

        public MoveGroupSequenceFeedback()
        {
            this.state = "";
        }

        public MoveGroupSequenceFeedback(string state)
        {
            this.state = state;
        }
    }
}
