/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class GetPositionFKResponse : Message
    {
        public const string RosMessageName = "moveit_msgs/srv/GetPositionFK";

        //  The resultant vector of PoseStamped messages that contains the (stamped) poses of the requested links
        public PoseStamped[] pose_stamped { get; set; }
        //  The list of link names corresponding to the poses
        public string[] fk_link_names { get; set; }
        public MoveItErrorCodes error_code { get; set; }

        public GetPositionFKResponse()
        {
            this.pose_stamped = new PoseStamped[0];
            this.fk_link_names = new string[0];
            this.error_code = new MoveItErrorCodes();
        }

        public GetPositionFKResponse(PoseStamped[] pose_stamped, string[] fk_link_names, MoveItErrorCodes error_code)
        {
            this.pose_stamped = pose_stamped;
            this.fk_link_names = fk_link_names;
            this.error_code = error_code;
        }
    }
}
#endif
