/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if !ROS2


namespace RosSharp.RosBridgeClient.MessageTypes.ActionlibTutorials
{
    public class AveragingAction : Action<AveragingActionGoal, AveragingActionResult, AveragingActionFeedback, AveragingGoal, AveragingResult, AveragingFeedback>
    {
        public const string RosMessageName = "actionlib_tutorials/AveragingAction";

        public AveragingAction() : base()
        {
            this.action_goal = new AveragingActionGoal();
            this.action_result = new AveragingActionResult();
            this.action_feedback = new AveragingActionFeedback();
        }

    }
}
#endif
