/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Moveit;

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class KinematicSolverInfo : Message
    {
        public override string RosMessageName => "moveit_msgs/KinematicSolverInfo";

        //  A list of joints in the kinematic tree
        public string[] joint_names { get; set; }
        //  A list of joint limits corresponding to the joint names
        public JointLimits[] limits { get; set; }
        //  A list of links that the kinematics node provides solutions for
        public string[] link_names { get; set; }

        public KinematicSolverInfo()
        {
            this.joint_names = new string[0];
            this.limits = new JointLimits[0];
            this.link_names = new string[0];
        }

        public KinematicSolverInfo(string[] joint_names, JointLimits[] limits, string[] link_names)
        {
            this.joint_names = joint_names;
            this.limits = limits;
            this.link_names = link_names;
        }
    }
}
