/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.ActionlibTutorials
{
    public class FibonacciActionFeedback : ActionFeedback<FibonacciFeedback>
    {
        public override string RosMessageName => "actionlib_tutorials/FibonacciActionFeedback";

        public FibonacciActionFeedback() : base()
        {
            this.feedback = new FibonacciFeedback();
        }

        public FibonacciActionFeedback(Header header, GoalStatus status, FibonacciFeedback feedback) : base(header, status)
        {
            this.feedback = feedback;
        }
    }
}
