/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.ActionlibTutorials
{
    public class FibonacciFeedback : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "actionlib_tutorials/FibonacciFeedback";

        //  feedback
        public int[] sequence;

        public FibonacciFeedback()
        {
            this.sequence = new int[0];
        }

        public FibonacciFeedback(int[] sequence)
        {
            this.sequence = sequence;
        }

        public override string ToString()
        {
            return JsonConvert.SerializeObject(this);
        }
    }
}
