/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.ActionlibTutorials
{
    public class FibonacciActionGoal : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "actionlib_tutorials/FibonacciActionGoal";

        public Header header;
        public GoalStatus status;
        public FibonacciGoal goal;

        public FibonacciActionGoal()
        {
            this.header = new Header();
            this.status = new GoalStatus();
            this.goal = new FibonacciGoal();
        }

        public FibonacciActionGoal(Header header, GoalStatus status, FibonacciGoal goal)
        {
            this.header = header;
            this.status = status;
            this.goal = goal;
        }
    }
}
