/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.ActionlibTutorials
{
    public class FibonacciActionResult : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "actionlib_tutorials/FibonacciActionResult";

        public Header header;
        public GoalStatus status;
        public FibonacciResult result;

        public FibonacciActionResult()
        {
            this.header = new Header();
            this.status = new GoalStatus();
            this.result = new FibonacciResult();
        }

        public FibonacciActionResult(Header header, GoalStatus status, FibonacciResult result)
        {
            this.header = header;
            this.status = status;
            this.result = result;
        }
    }
}
