/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.Sensor
{
    public class TimeReference : Message
    {
        public const string RosMessageName = "sensor_msgs/msg/TimeReference";

        //  Measurement from an external time source not actively synchronized with the system clock.
        public Header header { get; set; }
        //  stamp is system time for which measurement was valid
        //  frame_id is not used
        public Time time_ref { get; set; }
        //  corresponding time from this external source
        public string source { get; set; }
        //  (optional) name of time source

        public TimeReference()
        {
            this.header = new Header();
            this.time_ref = new Time();
            this.source = "";
        }

        public TimeReference(Header header, Time time_ref, string source)
        {
            this.header = header;
            this.time_ref = time_ref;
            this.source = source;
        }
    }
}
#endif
