/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2
//using RosSharp.RosBridgeClient.MessageTypes.Std;

//namespace RosSharp.RosBridgeClient.MessageTypes.ActionTutorialsInterfaces
//{
//    public class FibonacciActionFeedbackNew : ActionFeedback<FibonacciFeedback>
//    {
//        public const string RosMessageName = "action_tutorials_interfaces/FibonacciActionFeedback";

//        public FibonacciActionFeedbackNew() : base()
//        {
//            this.values = new FibonacciFeedback();
//        }

//        public FibonacciActionFeedbackNew(Header header, string id, string action, FibonacciFeedback feedback) : base(header, id, action)
//        {
//            this.values = feedback;
//        }
//    }
//}
#endif
