/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if !ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.Actionlib
{
    public class TestRequestActionFeedback : Message
    {
        public const string RosMessageName = "actionlib/TestRequestActionFeedback";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public Header header { get; set; }
        public GoalStatus status { get; set; }
        public TestRequestFeedback feedback { get; set; }

        public TestRequestActionFeedback()
        {
            this.header = new Header();
            this.status = new GoalStatus();
            this.feedback = new TestRequestFeedback();
        }

        public TestRequestActionFeedback(Header header, GoalStatus status, TestRequestFeedback feedback)
        {
            this.header = header;
            this.status = status;
            this.feedback = feedback;
        }
    }
}
#endif
