/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces
{
    public class Time : Message
    {
        public const string RosMessageName = "builtin_interfaces/msg/Time";

        //  This message communicates ROS Time defined here:
        //  https://design.ros2.org/articles/clock_and_time.html
        //  The seconds component, valid over all int32 values.
        public int sec { get; set; }
        //  The nanoseconds component, valid in the range [0, 10e9).
        public uint nanosec { get; set; }

        public Time()
        {
            this.sec = 0;
            this.nanosec = 0;
        }

        public Time(int sec, uint nanosec)
        {
            this.sec = sec;
            this.nanosec = nanosec;
        }
    }
}
#endif
