/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using System.Runtime.Serialization;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Actionlib
{
    [DataContract]
    public class GoalID : Message
    {
        [IgnoreDataMember]
        public const string RosMessageName = "actionlib_msgs/GoalID";

        //  The stamp should store the time at which this goal was requested.
        //  It is used by an action server when it tries to preempt all
        //  goals that were requested before a certain time
        [DataMember]
        public Time stamp;
        //  The id provides a way to associate feedback and
        //  result message with specific goal requests. The id
        //  specified must be unique.
        [DataMember]
        public string id;

        public GoalID()
        {
            this.stamp = new Time();
            this.id = "";
        }

        public GoalID(Time stamp, string id)
        {
            this.stamp = stamp;
            this.id = id;
        }
    }
}
