/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2
using RosSharp.RosBridgeClient.MessageTypes.Std;
namespace RosSharp.RosBridgeClient.MessageTypes.ObjectRecognition
{
    public class ObjectRecognitionActionFeedback : ActionFeedback<ObjectRecognitionFeedback>
    {
        public const string RosMessageName = "object_recognition_msgs/action/ObjectRecognitionActionFeedback";

        public ObjectRecognitionActionFeedback() : base()
        {
            this.values = new ObjectRecognitionFeedback();
        }

        public ObjectRecognitionActionFeedback(Header header, string id, string action, ObjectRecognitionFeedback values) : base(header, id, action)
        {
            this.values = values;
        }
    }
}
#endif
