/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

namespace RosSharp.RosBridgeClient.MessageTypes.Std
{
    public class Float64 : Message
    {
        public override string RosMessageName => "std_msgs/Float64";

        public double data { get; set; }

        public Float64()
        {
            this.data = 0.0;
        }

        public Float64(double data)
        {
            this.data = data;
        }
    }
}
