/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using System.Runtime.Serialization;

namespace RosSharp.RosBridgeClient.MessageTypes.Std
{
    [DataContract]
    public class UInt64 : Message
    {
        [IgnoreDataMember]
        public const string RosMessageName = "std_msgs/UInt64";

        [DataMember]
        public ulong data;

        public UInt64()
        {
            this.data = 0;
        }

        public UInt64(ulong data)
        {
            this.data = data;
        }
    }
}
