/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Moveit;

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class HybridPlannerGoal : Message
    {
        public const string RosMessageName = "moveit_msgs/action/HybridPlannerGoal";

        //  Motion planning request to the hybrid planning architecture
        public string planning_group { get; set; }
        public MotionSequenceRequest motion_sequence { get; set; }

        public HybridPlannerGoal()
        {
            this.planning_group = "";
            this.motion_sequence = new MotionSequenceRequest();
        }

        public HybridPlannerGoal(string planning_group, MotionSequenceRequest motion_sequence)
        {
            this.planning_group = planning_group;
            this.motion_sequence = motion_sequence;
        }
    }
}
#endif
