/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class LocalPlannerGoal : Message
    {
        public const string RosMessageName = "moveit_msgs/action/LocalPlannerGoal";

        //  Local constraints to apply when following the target trajectory produced by the GlobalPlanner
        public Constraints[] local_constraints { get; set; }

        public LocalPlannerGoal()
        {
            this.local_constraints = new Constraints[0];
        }

        public LocalPlannerGoal(Constraints[] local_constraints)
        {
            this.local_constraints = local_constraints;
        }
    }
}
#endif
