/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2
using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class MoveGroupActionFeedback : ActionFeedback<MoveGroupFeedback>
    {
        public const string RosMessageName = "moveit_msgs/MoveGroupActionFeedback";

        public MoveGroupActionFeedback() : base()
        {
            this.feedback = new MoveGroupFeedback();
        }

        public MoveGroupActionFeedback(Header header, GoalStatus status, MoveGroupFeedback feedback) : base(header, status)
        {
            this.feedback = feedback;
        }
    }
}
#endif
