/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2


namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class MoveGroupSequenceAction : Action<MoveGroupSequenceActionGoal, MoveGroupSequenceActionResult, MoveGroupSequenceActionFeedback, MoveGroupSequenceGoal, MoveGroupSequenceResult, MoveGroupSequenceFeedback>
    {
        public const string RosMessageName = "moveit_msgs/action/MoveGroupSequenceAction";

        public MoveGroupSequenceAction() : base()
        {
            this.action_goal = new MoveGroupSequenceActionGoal();
            this.action_result = new MoveGroupSequenceActionResult();
            this.action_feedback = new MoveGroupSequenceActionFeedback();
        }

    }
}
#endif
