/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2
using RosSharp.RosBridgeClient.MessageTypes.Std;
namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class PickupActionFeedback : ActionFeedback<PickupFeedback>
    {
        public const string RosMessageName = "moveit_msgs/action/PickupActionFeedback";

        public PickupActionFeedback() : base()
        {
            this.values = new PickupFeedback();
        }

        public PickupActionFeedback(Header header, string id, string action, PickupFeedback values) : base(header, id, action)
        {
            this.values = values;
        }
    }
}
#endif
