/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if !ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Geometry
{
    public class Polygon : Message
    {
        public const string RosMessageName = "geometry_msgs/Polygon";

        // A specification of a polygon where the first and last points are assumed to be connected
        public Point32[] points { get; set; }

        public Polygon()
        {
            this.points = new Point32[0];
        }

        public Polygon(Point32[] points)
        {
            this.points = points;
        }
    }
}
#endif
