/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if !ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class AllowedCollisionMatrix : Message
    {
        public const string RosMessageName = "moveit_msgs/AllowedCollisionMatrix";

        //  The list of entry names in the matrix
        public string[] entry_names { get; set; }
        //  The individual entries in the allowed collision matrix
        //  square, symmetric, with same order as entry_names
        public AllowedCollisionEntry[] entry_values { get; set; }
        //  In addition to the collision matrix itself, we also have
        //  the default entry value for each entry name.
        //  If the allowed collision flag is queried for a pair of names (n1, n2)
        //  that is not found in the collision matrix itself, the value of
        //  the collision flag is considered to be that of the entry (n1 or n2)
        //  specified in the list below. If both n1 and n2 are found in the list
        //  of defaults, the result is computed with an AND operation
        public string[] default_entry_names { get; set; }
        public bool[] default_entry_values { get; set; }

        public AllowedCollisionMatrix()
        {
            this.entry_names = new string[0];
            this.entry_values = new AllowedCollisionEntry[0];
            this.default_entry_names = new string[0];
            this.default_entry_values = new bool[0];
        }

        public AllowedCollisionMatrix(string[] entry_names, AllowedCollisionEntry[] entry_values, string[] default_entry_names, bool[] default_entry_values)
        {
            this.entry_names = entry_names;
            this.entry_values = entry_values;
            this.default_entry_names = default_entry_names;
            this.default_entry_values = default_entry_values;
        }
    }
}
#endif
