/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if !ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class Constraints : Message
    {
        public const string RosMessageName = "moveit_msgs/Constraints";

        //  This message contains a list of motion planning constraints.
        //  All constraints must be satisfied for a goal to be considered valid
        public string name { get; set; }
        public JointConstraint[] joint_constraints { get; set; }
        public PositionConstraint[] position_constraints { get; set; }
        public OrientationConstraint[] orientation_constraints { get; set; }
        public VisibilityConstraint[] visibility_constraints { get; set; }

        public Constraints()
        {
            this.name = "";
            this.joint_constraints = new JointConstraint[0];
            this.position_constraints = new PositionConstraint[0];
            this.orientation_constraints = new OrientationConstraint[0];
            this.visibility_constraints = new VisibilityConstraint[0];
        }

        public Constraints(string name, JointConstraint[] joint_constraints, PositionConstraint[] position_constraints, OrientationConstraint[] orientation_constraints, VisibilityConstraint[] visibility_constraints)
        {
            this.name = name;
            this.joint_constraints = joint_constraints;
            this.position_constraints = position_constraints;
            this.orientation_constraints = orientation_constraints;
            this.visibility_constraints = visibility_constraints;
        }
    }
}
#endif
