/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if !ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Trajectory;
using RosSharp.RosBridgeClient.MessageTypes.Moveit;

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class GenericTrajectory : Message
    {
        public const string RosMessageName = "moveit_msgs/GenericTrajectory";

        //  A generic trajectory message that may either encode a joint- or cartesian-space trajectory, or both
        //  Trajectories encoded in this message are considered semantically equivalent
        public Header header { get; set; }
        public JointTrajectory[] joint_trajectory { get; set; }
        public CartesianTrajectory[] cartesian_trajectory { get; set; }

        public GenericTrajectory()
        {
            this.header = new Header();
            this.joint_trajectory = new JointTrajectory[0];
            this.cartesian_trajectory = new CartesianTrajectory[0];
        }

        public GenericTrajectory(Header header, JointTrajectory[] joint_trajectory, CartesianTrajectory[] cartesian_trajectory)
        {
            this.header = header;
            this.joint_trajectory = joint_trajectory;
            this.cartesian_trajectory = cartesian_trajectory;
        }
    }
}
#endif
