/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if !ROS2

using RosSharp.RosBridgeClient.MessageTypes.ObjectRecognition;

namespace RosSharp.RosBridgeClient.MessageTypes.ObjectRecognition
{
    public class GetObjectInformationResponse : Message
    {
        public const string RosMessageName = "object_recognition_msgs/GetObjectInformation";

        //  Extra object info 
        public ObjectInformation information { get; set; }

        public GetObjectInformationResponse()
        {
            this.information = new ObjectInformation();
        }

        public GetObjectInformationResponse(ObjectInformation information)
        {
            this.information = information;
        }
    }
}
#endif
