/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.FileServer
{
    public class SaveBinaryFileRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "file_server/SaveBinaryFile";

        public string name;
        public byte[] value;

        public SaveBinaryFileRequest()
        {
            this.name = "";
            this.value = new byte[0];
        }

        public SaveBinaryFileRequest(string name, byte[] value)
        {
            this.name = name;
            this.value = value;
        }

        public override string ToString()
        {
            return JsonConvert.SerializeObject(this);
        }
    }
}
