/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

namespace RosSharp.RosBridgeClient.MessageTypes.FileServer
{
    public class GetBinaryFileResponse : Message
    {
        public const string RosMessageName = "file_server/GetBinaryFile";

        public byte[] value { get; set; }

        public GetBinaryFileResponse()
        {
            this.value = new byte[0];
        }

        public GetBinaryFileResponse(byte[] value)
        {
            this.value = value;
        }
    }
}
