/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class ChangeControlDimensionsResponse : Message
    {
        public string RosMessageName { get { return "moveit_msgs/ChangeControlDimensions"; } }

        public bool success { get; set; }

        public ChangeControlDimensionsResponse()
        {
            this.success = false;
        }

        public ChangeControlDimensionsResponse(bool success)
        {
            this.success = success;
        }
    }
}
