/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class GetPositionIKResponse : Message
    {
        public override string RosMessageName => "moveit_msgs/GetPositionIK";

        //  The returned solution 
        //  (in the same order as the list of joints specified in the IKRequest message)
        public RobotState solution { get; set; }
        public MoveItErrorCodes error_code { get; set; }

        public GetPositionIKResponse()
        {
            this.solution = new RobotState();
            this.error_code = new MoveItErrorCodes();
        }

        public GetPositionIKResponse(RobotState solution, MoveItErrorCodes error_code)
        {
            this.solution = solution;
            this.error_code = error_code;
        }
    }
}
