/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class GetPlannerParamsRequest : Message
    {
        public const string RosMessageName = "moveit_msgs/GetPlannerParams";

        //  Name of planning config
        public string planner_config { get; set; }
        //  Optional name of planning group (return global defaults if empty)
        public string group { get; set; }

        public GetPlannerParamsRequest()
        {
            this.planner_config = "";
            this.group = "";
        }

        public GetPlannerParamsRequest(string planner_config, string group)
        {
            this.planner_config = planner_config;
            this.group = group;
        }
    }
}
