/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class QueryPlannerInterfacesResponse : Message
    {
        public override string RosMessageName => "moveit_msgs/QueryPlannerInterfaces";

        //  The planning instances that could be used in the benchmark
        public PlannerInterfaceDescription[] planner_interfaces { get; set; }

        public QueryPlannerInterfacesResponse()
        {
            this.planner_interfaces = new PlannerInterfaceDescription[0];
        }

        public QueryPlannerInterfacesResponse(PlannerInterfaceDescription[] planner_interfaces)
        {
            this.planner_interfaces = planner_interfaces;
        }
    }
}
