/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Moveit;

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class SaveRobotStateToWarehouseRequest : Message
    {
        public override string RosMessageName => "moveit_msgs/SaveRobotStateToWarehouse";

        public string name { get; set; }
        public string robot { get; set; }
        public RobotState state { get; set; }

        public SaveRobotStateToWarehouseRequest()
        {
            this.name = "";
            this.robot = "";
            this.state = new RobotState();
        }

        public SaveRobotStateToWarehouseRequest(string name, string robot, RobotState state)
        {
            this.name = name;
            this.robot = robot;
            this.state = state;
        }
    }
}
