/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2
using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.Tf2
{
    public class LookupTransformActionGoal : ActionGoal<LookupTransformGoal>
    {
        public const string RosMessageName = "tf2_msgs/LookupTransformActionGoal";

        public LookupTransformActionGoal() : base()
        {
            this.goal = new LookupTransformGoal();
        }

        public LookupTransformActionGoal(Header header, GoalID goal_id, LookupTransformGoal goal) : base(header, goal_id)
        {
            this.goal = goal;
        }
    }
}
#endif
