/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2
using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Action;

namespace RosSharp.RosBridgeClient.MessageTypes.Tf2
{
    public class LookupTransformActionGoal : ActionGoal<LookupTransformGoal>
    {
        public const string RosMessageName = "tf2_msgs/action/LookupTransformActionGoal";

        public LookupTransformActionGoal() : base()
        {
            this.args = new LookupTransformGoal();
        }

        public LookupTransformActionGoal(Header header, GoalInfo goalInfo, LookupTransformGoal args) : base(header, goalInfo)
        {
            this.args = args;
        }
    }
}
#endif
