/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2
using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Action;

namespace RosSharp.RosBridgeClient.MessageTypes.Tf2
{
    public class LookupTransformActionFeedback : ActionFeedback<LookupTransformFeedback>
    {
        public const string RosMessageName = "tf2_msgs/action/LookupTransformActionFeedback";

        public LookupTransformActionFeedback() : base()
        {
            this.values = new LookupTransformFeedback();
        }

        public LookupTransformActionFeedback(Header header, string id, string action, LookupTransformFeedback values) : base(header, id, action)
        {
            this.values = values;
        }
    }
}
#endif
