/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2
using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Action;

namespace RosSharp.RosBridgeClient.MessageTypes.ObjectRecognition
{
    public class ObjectRecognitionActionGoal : ActionGoal<ObjectRecognitionGoal>
    {
        public const string RosMessageName = "object_recognition_msgs/action/ObjectRecognitionActionGoal";

        public ObjectRecognitionActionGoal() : base()
        {
            this.args = new ObjectRecognitionGoal();
        }

        public ObjectRecognitionActionGoal(Header header, GoalInfo goalInfo, ObjectRecognitionGoal args) : base(header, goalInfo)
        {
            this.args = args;
        }
    }
}
#endif
