/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Rosapi
{
    public class ServiceRequestDetails_Response : Message
    {
        public const string RosMessageName = "rosapi_msgs/msg/ServiceRequestDetails_Response";

        public TypeDef[] typedefs { get; set; }

        public ServiceRequestDetails_Response()
        {
            this.typedefs = new TypeDef[0];
        }

        public ServiceRequestDetails_Response(TypeDef[] typedefs)
        {
            this.typedefs = typedefs;
        }
    }
}
#endif
