/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Rosapi
{
    public class Topics_Response : Message
    {
        public const string RosMessageName = "rosapi_msgs/msg/Topics_Response";

        public string[] topics { get; set; }
        public string[] types { get; set; }

        public Topics_Response()
        {
            this.topics = new string[0];
            this.types = new string[0];
        }

        public Topics_Response(string[] topics, string[] types)
        {
            this.topics = topics;
            this.types = types;
        }
    }
}
#endif
