/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;

#if !ROS2
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;
using RosSharp.RosBridgeClient.MessageTypes.ActionlibTutorials;

namespace RosSharp.RosBridgeClient.MessageTypes.ActionTutorialsInterfaces
{
    public class FibonacciActionResult : ActionResult<FibonacciResult>
    {
        public const string RosMessageName = "action_tutorials_interfaces/FibonacciActionResult";

        public FibonacciActionResult() : base()
        {
            this.result = new FibonacciResult();
        }

        public FibonacciActionResult(Header header, GoalStatus status, FibonacciResult result) : base(header, status)
        {
            this.result = result;
        }
    }
}

#else
namespace RosSharp.RosBridgeClient.MessageTypes.ActionTutorialsInterfaces
{
    public class FibonacciActionResult : ActionResult<FibonacciResult>
    {
        public const string RosMessageName = "action_tutorials_interfaces/action/FibonacciActionResult";

        public FibonacciActionResult() : base()
        {
            this.values = new FibonacciResult();
        }


        public FibonacciActionResult(Header header, string action, sbyte status, bool result, string id, FibonacciResult values) : base(header, action, status, result, id)
        {
            this.values = values;
        }
    }
}
#endif