/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2
using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.ActionTutorialsInterfaces
{
    public class FibonacciActionResult : ActionResult<FibonacciResult>
    {
        public const string RosMessageName = "action_tutorials_interfaces/FibonacciActionResult";

        public FibonacciActionResult() : base()
        {
            this.result = new FibonacciResult();
        }

        public FibonacciActionResult(Header header, GoalStatus status, FibonacciResult result) : base(header, status)
        {
            this.result = result;
        }
    }
}
#endif
