/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if !ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class GetCartesianPathResponse : Message
    {
        public const string RosMessageName = "moveit_msgs/GetCartesianPath";

        //  The state at which the computed path starts
        public RobotState start_state { get; set; }
        //  The computed solution trajectory, for the desired group, in configuration space
        public RobotTrajectory solution { get; set; }
        //  If the computation was incomplete, this value indicates the fraction of the path
        //  that was in fact computed (number of waypoints traveled through)
        public double fraction { get; set; }
        //  The error code of the computation
        public MoveItErrorCodes error_code { get; set; }

        public GetCartesianPathResponse()
        {
            this.start_state = new RobotState();
            this.solution = new RobotTrajectory();
            this.fraction = 0.0;
            this.error_code = new MoveItErrorCodes();
        }

        public GetCartesianPathResponse(RobotState start_state, RobotTrajectory solution, double fraction, MoveItErrorCodes error_code)
        {
            this.start_state = start_state;
            this.solution = solution;
            this.fraction = fraction;
            this.error_code = error_code;
        }
    }
}
#endif
