/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.Tf2
{
    public class LookupTransformActionFeedback : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "tf2_msgs/LookupTransformActionFeedback";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public Header header;
        public GoalStatus status;
        public LookupTransformFeedback feedback;

        public LookupTransformActionFeedback()
        {
            this.header = new Header();
            this.status = new GoalStatus();
            this.feedback = new LookupTransformFeedback();
        }

        public LookupTransformActionFeedback(Header header, GoalStatus status, LookupTransformFeedback feedback)
        {
            this.header = header;
            this.status = status;
            this.feedback = feedback;
        }
    }
}
