/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Geometry;
using RosSharp.RosBridgeClient.MessageTypes.Tf2;

namespace RosSharp.RosBridgeClient.MessageTypes.Tf2
{
    public class LookupTransformResult : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "tf2_msgs/LookupTransformResult";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public TransformStamped transform;
        public TF2Error error;

        public LookupTransformResult()
        {
            this.transform = new TransformStamped();
            this.error = new TF2Error();
        }

        public LookupTransformResult(TransformStamped transform, TF2Error error)
        {
            this.transform = transform;
            this.error = error;
        }

        public override string ToString()
        {
            return JsonConvert.SerializeObject(this);
        }
    }
}
