/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using System.Runtime.Serialization;

namespace RosSharp.RosBridgeClient.MessageTypes.Tf2
{
    [DataContract]
    public class LookupTransformAction : Message
    {
        [IgnoreDataMember]
        public const string RosMessageName = "tf2_msgs/LookupTransformAction";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        [DataMember]
        public LookupTransformActionGoal action_goal;
        [DataMember]
        public LookupTransformActionResult action_result;
        [DataMember]
        public LookupTransformActionFeedback action_feedback;

        public LookupTransformAction()
        {
            this.action_goal = new LookupTransformActionGoal();
            this.action_result = new LookupTransformActionResult();
            this.action_feedback = new LookupTransformActionFeedback();
        }

        public LookupTransformAction(LookupTransformActionGoal action_goal, LookupTransformActionResult action_result, LookupTransformActionFeedback action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }
    }
}
