/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using System.Runtime.Serialization;

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Tf2
{
    [DataContract]
    public class TFMessage : Message
    {
        [IgnoreDataMember]
        public const string RosMessageName = "tf2_msgs/TFMessage";

        [DataMember]
        public TransformStamped[] transforms;

        public TFMessage()
        {
            this.transforms = new TransformStamped[0];
        }

        public TFMessage(TransformStamped[] transforms)
        {
            this.transforms = transforms;
        }
    }
}
