/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav
{
    public class Goals : Message
    {
        public const string RosMessageName = "nav_msgs/msg/Goals";

        //  An array of navigation goals
        //  This header will store the time at which the poses were computed (not to be confused with the stamps of the poses themselves)
        //  In the case that individual poses do not have their frame_id set or their timetamp set they will use the default value here.
        public Header header { get; set; }
        //  An array of goals to for navigation to achieve.
        //  The goals should be executed in the order of the array.
        //  The header and stamp are intended to be used for computing the position of the goals.
        //  They may vary to support cases of goals that are moving with respect to the robot.
        public PoseStamped[] goals { get; set; }

        public Goals()
        {
            this.header = new Header();
            this.goals = new PoseStamped[0];
        }

        public Goals(Header header, PoseStamped[] goals)
        {
            this.header = header;
            this.goals = goals;
        }
    }
}
#endif
