/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav
{
    public class GridCells : Message
    {
        public const string RosMessageName = "nav_msgs/msg/GridCells";

        //  An array of cells in a 2D grid
        public Header header { get; set; }
        //  Width of each cell
        public float cell_width { get; set; }
        //  Height of each cell
        public float cell_height { get; set; }
        //  Each cell is represented by the Point at the center of the cell
        public Point[] cells { get; set; }

        public GridCells()
        {
            this.header = new Header();
            this.cell_width = 0.0f;
            this.cell_height = 0.0f;
            this.cells = new Point[0];
        }

        public GridCells(Header header, float cell_width, float cell_height, Point[] cells)
        {
            this.header = header;
            this.cell_width = cell_width;
            this.cell_height = cell_height;
            this.cells = cells;
        }
    }
}
#endif
