/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Sensor
{
    public class Joy : Message
    {
        public const string RosMessageName = "sensor_msgs/msg/Joy";

        //  Reports the state of a joystick's axes and buttons.
        //  The timestamp is the time at which data is received from the joystick.
        public Header header { get; set; }
        //  The axes measurements from a joystick.
        public float[] axes { get; set; }
        //  The buttons measurements from a joystick.
        public int[] buttons { get; set; }

        public Joy()
        {
            this.header = new Header();
            this.axes = new float[0];
            this.buttons = new int[0];
        }

        public Joy(Header header, float[] axes, int[] buttons)
        {
            this.header = header;
            this.axes = axes;
            this.buttons = buttons;
        }
    }
}
#endif
