/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using System.Runtime.Serialization;

namespace RosSharp.RosBridgeClient.MessageTypes.Rosapi
{
    [DataContract]
    public class TypeDef : Message
    {
        [IgnoreDataMember]
        public const string RosMessageName = "rosapi/TypeDef";

        [DataMember]
        public string type;
        [DataMember]
        public string[] fieldnames;
        [DataMember]
        public string[] fieldtypes;
        [DataMember]
        public int[] fieldarraylen;
        [DataMember]
        public string[] examples;
        [DataMember]
        public string[] constnames;
        [DataMember]
        public string[] constvalues;

        public TypeDef()
        {
            this.type = "";
            this.fieldnames = new string[0];
            this.fieldtypes = new string[0];
            this.fieldarraylen = new int[0];
            this.examples = new string[0];
            this.constnames = new string[0];
            this.constvalues = new string[0];
        }

        public TypeDef(string type, string[] fieldnames, string[] fieldtypes, int[] fieldarraylen, string[] examples, string[] constnames, string[] constvalues)
        {
            this.type = type;
            this.fieldnames = fieldnames;
            this.fieldtypes = fieldtypes;
            this.fieldarraylen = fieldarraylen;
            this.examples = examples;
            this.constnames = constnames;
            this.constvalues = constvalues;
        }
    }
}
