/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Rosapi
{
    public class TypeDef : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "rosapi/TypeDef";

        public string type;
        public string[] fieldnames;
        public string[] fieldtypes;
        public int[] fieldarraylen;
        public string[] examples;

        public TypeDef()
        {
            this.type = "";
            this.fieldnames = new string[0];
            this.fieldtypes = new string[0];
            this.fieldarraylen = new int[0];
            this.examples = new string[0];
        }

        public TypeDef(string type, string[] fieldnames, string[] fieldtypes, int[] fieldarraylen, string[] examples)
        {
            this.type = type;
            this.fieldnames = fieldnames;
            this.fieldtypes = fieldtypes;
            this.fieldarraylen = fieldarraylen;
            this.examples = examples;
        }
    }
}
