/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2


namespace RosSharp.RosBridgeClient.MessageTypes.Tf2
{
    public class LookupTransformAction : Action<LookupTransformActionGoal, LookupTransformActionResult, LookupTransformActionFeedback, LookupTransformGoal, LookupTransformResult, LookupTransformFeedback>
    {
        public const string RosMessageName = "tf2_msgs/action/LookupTransformAction";

        public LookupTransformAction() : base()
        {
            this.action_goal = new LookupTransformActionGoal();
            this.action_result = new LookupTransformActionResult();
            this.action_feedback = new LookupTransformActionFeedback();
        }

    }
}
#endif
