/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.Tf2
{
    public class LookupTransformGoal : Message
    {
        public const string RosMessageName = "tf2_msgs/action/LookupTransformGoal";

        // Simple API
        public string target_frame { get; set; }
        public string source_frame { get; set; }
        public Time source_time { get; set; }
        public Duration timeout { get; set; }
        // Advanced API
        public Time target_time { get; set; }
        public string fixed_frame { get; set; }
        // Whether or not to use the advanced API
        public bool advanced { get; set; }

        public LookupTransformGoal()
        {
            this.target_frame = "";
            this.source_frame = "";
            this.source_time = new Time();
            this.timeout = new Duration();
            this.target_time = new Time();
            this.fixed_frame = "";
            this.advanced = false;
        }

        public LookupTransformGoal(string target_frame, string source_frame, Time source_time, Duration timeout, Time target_time, string fixed_frame, bool advanced)
        {
            this.target_frame = target_frame;
            this.source_frame = source_frame;
            this.source_time = source_time;
            this.timeout = timeout;
            this.target_time = target_time;
            this.fixed_frame = fixed_frame;
            this.advanced = advanced;
        }
    }
}
#endif
