/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class GripperTranslation : Message
    {
        public const string RosMessageName = "moveit_msgs/GripperTranslation";

        //  defines a translation for the gripper, used in pickup or place tasks
        //  for example for lifting an object off a table or approaching the table for placing
        //  the direction of the translation
        public Vector3Stamped direction { get; set; }
        //  the desired translation distance
        public float desired_distance { get; set; }
        //  the min distance that must be considered feasible before the
        //  grasp is even attempted
        public float min_distance { get; set; }

        public GripperTranslation()
        {
            this.direction = new Vector3Stamped();
            this.desired_distance = 0.0f;
            this.min_distance = 0.0f;
        }

        public GripperTranslation(Vector3Stamped direction, float desired_distance, float min_distance)
        {
            this.direction = direction;
            this.desired_distance = desired_distance;
            this.min_distance = min_distance;
        }
    }
}
