/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Geometry
{
    public class Vector3 : Message
    {
        public const string RosMessageName = "geometry_msgs/msg/Vector3";

        //  This represents a vector in free space.
        //  This is semantically different than a point.
        //  A vector is always anchored at the origin.
        //  When a transform is applied to a vector, only the rotational component is applied.
        public double x { get; set; }
        public double y { get; set; }
        public double z { get; set; }

        public Vector3()
        {
            this.x = 0.0;
            this.y = 0.0;
            this.z = 0.0;
        }

        public Vector3(double x, double y, double z)
        {
            this.x = x;
            this.y = y;
            this.z = z;
        }
    }
}
#endif
