/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if !ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.ObjectRecognition;

namespace RosSharp.RosBridgeClient.MessageTypes.ObjectRecognition
{
    public class RecognizedObjectArray : Message
    {
        public const string RosMessageName = "object_recognition_msgs/RecognizedObjectArray";

        // #################################################### HEADER ###########################################################
        public Header header { get; set; }
        //  This message type describes a potential scene configuration: a set of objects that can explain the scene
        public RecognizedObject[] objects { get; set; }
        // #################################################### SEARCH ###########################################################
        //  The co-occurrence matrix between the recognized objects
        public float[] cooccurrence { get; set; }

        public RecognizedObjectArray()
        {
            this.header = new Header();
            this.objects = new RecognizedObject[0];
            this.cooccurrence = new float[0];
        }

        public RecognizedObjectArray(Header header, RecognizedObject[] objects, float[] cooccurrence)
        {
            this.header = header;
            this.objects = objects;
            this.cooccurrence = cooccurrence;
        }
    }
}
#endif
