/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class JointConstraint : Message
    {
        public const string RosMessageName = "moveit_msgs/msg/JointConstraint";

        //  Constrain the position of a joint to be within a certain bound
        public string joint_name { get; set; }
        //  the bound to be achieved is [position - tolerance_below, position + tolerance_above]
        public double position { get; set; }
        public double tolerance_above { get; set; }
        public double tolerance_below { get; set; }
        //  A weighting factor for this constraint (denotes relative importance to other constraints. Closer to zero means less important)
        public double weight { get; set; }

        public JointConstraint()
        {
            this.joint_name = "";
            this.position = 0.0;
            this.tolerance_above = 0.0;
            this.tolerance_below = 0.0;
            this.weight = 0.0;
        }

        public JointConstraint(string joint_name, double position, double tolerance_above, double tolerance_below, double weight)
        {
            this.joint_name = joint_name;
            this.position = position;
            this.tolerance_above = tolerance_above;
            this.tolerance_below = tolerance_below;
            this.weight = weight;
        }
    }
}
#endif
