/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Tf2
{
    public class FrameGraphResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "tf2_msgs/FrameGraph";

        public string frame_yaml;

        public FrameGraphResponse()
        {
            this.frame_yaml = "";
        }

        public FrameGraphResponse(string frame_yaml)
        {
            this.frame_yaml = frame_yaml;
        }

        public override string ToString()
        {
            return JsonConvert.SerializeObject(this);
        }
    }
}
