/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if !ROS2
using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class MoveGroupActionResult : ActionResult<MoveGroupResult>
    {
        public const string RosMessageName = "moveit_msgs/MoveGroupActionResult";

        public MoveGroupActionResult() : base()
        {
            this.result = new MoveGroupResult();
        }

        public MoveGroupActionResult(Header header, GoalStatus status, MoveGroupResult result) : base(header, status)
        {
            this.result = result;
        }
    }
}
#endif
