/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

namespace RosSharp.RosBridgeClient.MessageTypes.Nav
{
    public class GetMapAction : Message
    {
        public const string RosMessageName = "nav_msgs/GetMapAction";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public GetMapActionGoal action_goal { get; set; }
        public GetMapActionResult action_result { get; set; }
        public GetMapActionFeedback action_feedback { get; set; }

        public GetMapAction()
        {
            this.action_goal = new GetMapActionGoal();
            this.action_result = new GetMapActionResult();
            this.action_feedback = new GetMapActionFeedback();
        }

        public GetMapAction(GetMapActionGoal action_goal, GetMapActionResult action_result, GetMapActionFeedback action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }
    }
}
