/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using System.Runtime.Serialization;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav
{
    [DataContract]
    public class GetMapActionResult : Message
    {
        [IgnoreDataMember]
        public const string RosMessageName = "nav_msgs/GetMapActionResult";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        [DataMember]
        public Header header;
        [DataMember]
        public GoalStatus status;
        [DataMember]
        public GetMapResult result;

        public GetMapActionResult()
        {
            this.header = new Header();
            this.status = new GoalStatus();
            this.result = new GetMapResult();
        }

        public GetMapActionResult(Header header, GoalStatus status, GetMapResult result)
        {
            this.header = header;
            this.status = status;
            this.result = result;
        }
    }
}
