/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using System.Runtime.Serialization;

using RosSharp.RosBridgeClient.MessageTypes.Nav;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav
{
    [DataContract]
    public class GetMapResponse : Message
    {
        [IgnoreDataMember]
        public const string RosMessageName = "nav_msgs/GetMap";

        [DataMember]
        public OccupancyGrid map;

        public GetMapResponse()
        {
            this.map = new OccupancyGrid();
        }

        public GetMapResponse(OccupancyGrid map)
        {
            this.map = map;
        }
    }
}
