/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav
{
    public class GetMapRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "nav_msgs/GetMap";

        //  Get the map as a nav_msgs/OccupancyGrid

        public GetMapRequest()
        {
        }

        public override string ToString()
        {
            return JsonConvert.SerializeObject(this);
        }
    }
}
