/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using System.Runtime.Serialization;

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav
{
    [DataContract]
    public class GetPlanRequest : Message
    {
        [IgnoreDataMember]
        public const string RosMessageName = "nav_msgs/GetPlan";

        //  Get a plan from the current position to the goal Pose 
        //  The start pose for the plan
        [DataMember]
        public PoseStamped start;
        //  The final pose of the goal position
        [DataMember]
        public PoseStamped goal;
        //  If the goal is obstructed, how many meters the planner can 
        //  relax the constraint in x and y before failing. 
        [DataMember]
        public float tolerance;

        public GetPlanRequest()
        {
            this.start = new PoseStamped();
            this.goal = new PoseStamped();
            this.tolerance = 0.0f;
        }

        public GetPlanRequest(PoseStamped start, PoseStamped goal, float tolerance)
        {
            this.start = start;
            this.goal = goal;
            this.tolerance = tolerance;
        }
    }
}
