/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Sensor
{
    public class CompressedImage : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "sensor_msgs/CompressedImage";

        //  This message contains a compressed image
        public Header header;
        //  Header timestamp should be acquisition time of image
        //  Header frame_id should be optical frame of camera
        //  origin of frame should be optical center of camera
        //  +x should point to the right in the image
        //  +y should point down in the image
        //  +z should point into to plane of the image
        public string format;
        //  Specifies the format of the data
        //    Acceptable values:
        //      jpeg, png
        public byte[] data;
        //  Compressed image buffer

        public CompressedImage()
        {
            this.header = new Header();
            this.format = "";
            this.data = new byte[0];
        }

        public CompressedImage(Header header, string format, byte[] data)
        {
            this.header = header;
            this.format = format;
            this.data = data;
        }
    }
}
