/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Sensor
{
    public class Joy : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "sensor_msgs/Joy";

        //  Reports the state of a joysticks axes and buttons.
        public Header header;
        //  timestamp in the header is the time the data is received from the joystick
        public float[] axes;
        //  the axes measurements from a joystick
        public int[] buttons;
        //  the buttons measurements from a joystick 

        public Joy()
        {
            this.header = new Header();
            this.axes = new float[0];
            this.buttons = new int[0];
        }

        public Joy(Header header, float[] axes, int[] buttons)
        {
            this.header = header;
            this.axes = axes;
            this.buttons = buttons;
        }
    }
}
