/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

namespace RosSharp.RosBridgeClient.MessageTypes.Sensor
{
    public class JoyFeedbackArray : Message
    {
        public override string RosMessageName => "sensor_msgs/JoyFeedbackArray";

        //  This message publishes values for multiple feedback at once. 
        public JoyFeedback[] array { get; set; }

        public JoyFeedbackArray()
        {
            this.array = new JoyFeedback[0];
        }

        public JoyFeedbackArray(JoyFeedback[] array)
        {
            this.array = array;
        }
    }
}
