/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using System.Runtime.Serialization;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Sensor
{
    [DataContract]
    public class TimeReference : Message
    {
        [IgnoreDataMember]
        public const string RosMessageName = "sensor_msgs/TimeReference";

        //  Measurement from an external time source not actively synchronized with the system clock.
        [DataMember]
        public Header header;
        //  stamp is system time for which measurement was valid
        //  frame_id is not used 
        [DataMember]
        public Time time_ref;
        //  corresponding time from this external source
        [DataMember]
        public string source;
        //  (optional) name of time source

        public TimeReference()
        {
            this.header = new Header();
            this.time_ref = new Time();
            this.source = "";
        }

        public TimeReference(Header header, Time time_ref, string source)
        {
            this.header = header;
            this.time_ref = time_ref;
            this.source = source;
        }
    }
}
