/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Rosapi
{
    public class GetROSVersionResponse : Message
    {
        public const string RosMessageName = "rosapi_msgs/srv/GetROSVersion";

        public byte version { get; set; }
        public string distro { get; set; }

        public GetROSVersionResponse()
        {
            this.version = 0;
            this.distro = "";
        }

        public GetROSVersionResponse(byte version, string distro)
        {
            this.version = version;
            this.distro = distro;
        }
    }
}
#endif
