/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class DisplayTrajectory : Message
    {
        public const string RosMessageName = "moveit_msgs/DisplayTrajectory";

        //  The model id for which this path has been generated
        public string model_id { get; set; }
        //  The representation of the path contains position values for all the joints that are moving along the path; a sequence of trajectories may be specified
        public RobotTrajectory[] trajectory { get; set; }
        //  The robot state is used to obtain positions for all/some of the joints of the robot. 
        //  It is used by the path display node to determine the positions of the joints that are not specified in the joint path message above. 
        //  If the robot state message contains joint position information for joints that are also mentioned in the joint path message, the positions in the joint path message will overwrite the positions specified in the robot state message. 
        public RobotState trajectory_start { get; set; }

        public DisplayTrajectory()
        {
            this.model_id = "";
            this.trajectory = new RobotTrajectory[0];
            this.trajectory_start = new RobotState();
        }

        public DisplayTrajectory(string model_id, RobotTrajectory[] trajectory, RobotState trajectory_start)
        {
            this.model_id = model_id;
            this.trajectory = trajectory;
            this.trajectory_start = trajectory_start;
        }
    }
}
