/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if !ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav
{
    public class Path : Message
    {
        public const string RosMessageName = "nav_msgs/Path";

        // An array of poses that represents a Path for a robot to follow
        public Header header { get; set; }
        public PoseStamped[] poses { get; set; }

        public Path()
        {
            this.header = new Header();
            this.poses = new PoseStamped[0];
        }

        public Path(Header header, PoseStamped[] poses)
        {
            this.header = header;
            this.poses = poses;
        }
    }
}
#endif
