/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if !ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.ActionlibTutorials
{
    public class AveragingResult : Message
    {
        public const string RosMessageName = "actionlib_tutorials/AveragingResult";

        // result definition
        public float mean { get; set; }
        public float std_dev { get; set; }

        public AveragingResult()
        {
            this.mean = 0.0f;
            this.std_dev = 0.0f;
        }

        public AveragingResult(float mean, float std_dev)
        {
            this.mean = mean;
            this.std_dev = std_dev;
        }
    }
}
#endif
