/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if !ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.ActionlibTutorials
{
    public class AveragingFeedback : Message
    {
        public const string RosMessageName = "actionlib_tutorials/AveragingFeedback";

        // feedback
        public int sample { get; set; }
        public float data { get; set; }
        public float mean { get; set; }
        public float std_dev { get; set; }

        public AveragingFeedback()
        {
            this.sample = 0;
            this.data = 0.0f;
            this.mean = 0.0f;
            this.std_dev = 0.0f;
        }

        public AveragingFeedback(int sample, float data, float mean, float std_dev)
        {
            this.sample = sample;
            this.data = data;
            this.mean = mean;
            this.std_dev = std_dev;
        }
    }
}
#endif
