/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if !ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class MoveGroupSequenceGoal : Message
    {
        public const string RosMessageName = "moveit_msgs/MoveGroupSequenceGoal";

        //  A list of motion commands - one for each section of the sequence
        public MotionSequenceRequest request { get; set; }
        //  Planning options
        public PlanningOptions planning_options { get; set; }

        public MoveGroupSequenceGoal()
        {
            this.request = new MotionSequenceRequest();
            this.planning_options = new PlanningOptions();
        }

        public MoveGroupSequenceGoal(MotionSequenceRequest request, PlanningOptions planning_options)
        {
            this.request = request;
            this.planning_options = planning_options;
        }
    }
}
#endif
