/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Rosapi
{
    public class GetParamRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "rosapi/GetParam";

        public string name;
        [JsonProperty("default")]
        public string _default;

        public GetParamRequest()
        {
            this.name = "";
            this._default = "";
        }

        public GetParamRequest(string name, string _default)
        {
            this.name = name;
            this._default = _default;
        }

        public override string ToString()
        {
            return JsonConvert.SerializeObject(this);
        }
    }
}
