/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Rosapi
{
    public class SearchParamResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "rosapi/SearchParam";

        public string global_name;

        public SearchParamResponse()
        {
            this.global_name = "";
        }

        public SearchParamResponse(string global_name)
        {
            this.global_name = global_name;
        }

        public override string ToString()
        {
            return JsonConvert.SerializeObject(this);
        }
    }
}
