/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

namespace RosSharp.RosBridgeClient.MessageTypes.Rosapi
{
    public class ServiceRequestDetailsResponse : Message
    {
        public const string RosMessageName = "rosapi/ServiceRequestDetails";

        public TypeDef[] typedefs { get; set; }

        public ServiceRequestDetailsResponse()
        {
            this.typedefs = new TypeDef[0];
        }

        public ServiceRequestDetailsResponse(TypeDef[] typedefs)
        {
            this.typedefs = typedefs;
        }
    }
}
