/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

namespace RosSharp.RosBridgeClient.MessageTypes.Rosapi
{
    public class SubscribersRequest : Message
    {
        public override string RosMessageName => "rosapi/Subscribers";

        public string topic { get; set; }

        public SubscribersRequest()
        {
            this.topic = "";
        }

        public SubscribersRequest(string topic)
        {
            this.topic = topic;
        }
    }
}
