/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Rosapi
{
    public class NodeDetails_Response : Message
    {
        public const string RosMessageName = "rosapi_msgs/msg/NodeDetails_Response";

        public string[] subscribing { get; set; }
        public string[] publishing { get; set; }
        public string[] services { get; set; }

        public NodeDetails_Response()
        {
            this.subscribing = new string[0];
            this.publishing = new string[0];
            this.services = new string[0];
        }

        public NodeDetails_Response(string[] subscribing, string[] publishing, string[] services)
        {
            this.subscribing = subscribing;
            this.publishing = publishing;
            this.services = services;
        }
    }
}
#endif
