/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class ConstraintEvalResult : Message
    {
        public const string RosMessageName = "moveit_msgs/msg/ConstraintEvalResult";

        //  This message contains result from constraint evaluation
        //  result specifies the result of constraint evaluation
        //  (true indicates state satisfies constraint, false indicates state violates constraint)
        //  if false, distance specifies a measure of the distance of the state from the constraint
        //  if true, distance is set to zero
        public bool result { get; set; }
        public double distance { get; set; }

        public ConstraintEvalResult()
        {
            this.result = false;
            this.distance = 0.0;
        }

        public ConstraintEvalResult(bool result, double distance)
        {
            this.result = result;
            this.distance = distance;
        }
    }
}
#endif
