/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class GetPlanningScene_Response : Message
    {
        public const string RosMessageName = "moveit_msgs/msg/GetPlanningScene_Response";

        public PlanningScene scene { get; set; }

        public GetPlanningScene_Response()
        {
            this.scene = new PlanningScene();
        }

        public GetPlanningScene_Response(PlanningScene scene)
        {
            this.scene = scene;
        }
    }
}
#endif
