/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class ListRobotStatesInWarehouse_Request : Message
    {
        public const string RosMessageName = "moveit_msgs/msg/ListRobotStatesInWarehouse_Request";

        public string regex { get; set; }
        public string robot { get; set; }

        public ListRobotStatesInWarehouse_Request()
        {
            this.regex = "";
            this.robot = "";
        }

        public ListRobotStatesInWarehouse_Request(string regex, string robot)
        {
            this.regex = regex;
            this.robot = robot;
        }
    }
}
#endif
