/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.FileServer
{
    public class FileTransferActionFeedback : ActionFeedback<FileTransferFeedback>
    {
        [JsonIgnore]
        public const string RosMessageName = "file_server/FileTransferActionFeedback";

        public FileTransferActionFeedback() : base()
        {
            this.feedback = new FileTransferFeedback();
        }

        public FileTransferActionFeedback(Header header, GoalStatus status, FileTransferFeedback feedback) : base(header, status)
        {
            this.feedback = feedback;
        }
    }
}
