/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.FileServer
{
    public class FileTransferGoal : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "file_server/FileTransferGoal";

        //  Siemens AG, 2019
        //  Author: Sifan Ye (sifan.ye@siemens.com)
        //  File Transfer Action used in File Transfer To/From Ros
        //  Goal Def
        public byte type;
        //  Type of file sending operation
        public const byte SINGLE = 0; //  Send a single file
        public const byte PACKAGE = 1; //  Send files of a package
        public const byte RECURSIVE = 2; //  Send all files in a directory (recursively)
        public string identifier;
        //  Either package_name/file_name for single file
        //      or package_name for package
        //      or path for directory
        public string[] extensions;
        //  Extensions of files to be transferred (e.g. .msg, .srv, .action)

        public FileTransferGoal()
        {
            this.type = 0;
            this.identifier = "";
            this.extensions = new string[0];
        }

        public FileTransferGoal(byte type, string identifier, string[] extensions)
        {
            this.type = type;
            this.identifier = identifier;
            this.extensions = extensions;
        }
    }
}
