/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.FileServer
{
    public class FileTransferFromRosActionResult : ActionResult<FileTransferFromRosResult>
    {
        [JsonIgnore]
        public const string RosMessageName = "file_server/FileTransferFromRosActionResult";

        public FileTransferFromRosActionResult() : base()
        {
            this.result = new FileTransferFromRosResult();
        }

        public FileTransferFromRosActionResult(Header header, GoalStatus status, FileTransferFromRosResult result) : base(header, status)
        {
            this.result = result;
        }
    }
}
