/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.FileServer
{
    public class FileTransferFeedback : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "file_server/FileTransferFeedback";

        //  Feedback def
        public short number;
        //  Totoal number of files to be transferred
        public short count;
        //  Count of files transferred
        public string path;
        //  Path of transferred file at origin
        public byte[] content;
        //  The content of the file in bytes

        public FileTransferFeedback()
        {
            this.number = 0;
            this.count = 0;
            this.path = "";
            this.content = new byte[0];
        }

        public FileTransferFeedback(short number, short count, string path, byte[] content)
        {
            this.number = number;
            this.count = count;
            this.path = path;
            this.content = content;
        }
    }
}
