/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class CheckIfRobotStateExistsInWarehouseResponse : Message
    {
        public const string RosMessageName = "moveit_msgs/CheckIfRobotStateExistsInWarehouse";

        public bool exists { get; set; }

        public CheckIfRobotStateExistsInWarehouseResponse()
        {
            this.exists = false;
        }

        public CheckIfRobotStateExistsInWarehouseResponse(bool exists)
        {
            this.exists = exists;
        }
    }
}
